### ISSUE TITLE
Tombol batal pada alert hapus dokumen tidak berfungsi

### ISSUE THREAD

**Issue by Wiliyantoro** [OpenSID/wiki-mobile#10]
Saat menghapus dokumen di aplikasi opensid muncul alert "yakin menghapus dokumen"
Saat tekan tombol batal dokumen terhapus
![Screenshot_2021-11-28-13-01-40-09_7bd1e93dfbd7033a92739b1867380b15](https://user-images.githubusercontent.com/44520382/143730449-1b04c16d-03d7-4c89-88ea-3c5649592577.jpg)

**Comment by apidong** [comment]
diperbaiki di https://github.com/OpenSID/mobile/pull/78
