### ISSUE TITLE
Sediakan tombol unduh dokumen pada surat yang sudah di tanda tangan digital

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-mobile#100]
saat ini di layanan mandiri sudah diterapkan unduh dokumen yang sudah ditanda tangan. 
di mobile juga perlu mengikuti agar menjadi konsisten antara layanan mandiri & mobile.

**Comment by yogiperdana** [comment]
> saat ini di layanan mandiri sudah diterapkan unduh dokumen yang sudah ditanda tangan. di mobile juga perlu mengikuti agar menjadi konsisten antara layanan mandiri & mobile.

Di layanan mandiri tidak ada mas. kemaren fitur ini eksklusif untuk anjungan. sekarang apakah tetap mau diterapkan di mobile? @vickyrolanda

**Comment by apidong** [comment]
sudah dikerjakan melalui https://github.com/OpenSID/mobile/pull/175
