### ISSUE TITLE
Perbaikan tulisan Kabupaten menjadi Kota di mobile

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-mobile#102]
![image](https://github.com/OpenSID/wiki-mobile/assets/59082428/beb19469-57ac-4131-998e-0dfe2e7d1fec)

**Comment by eddieridwan** [comment]
@vickyrolanda sesuaikan dengan kode wilayah. Kode wilayah akan menentukan apakah kabupaten atau kota. Tidak perlu melalui pengaturan.

**Comment by yogiperdana** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/mobile/pull/173
