### ISSUE TITLE
Data Bantuan tidak muncul sedangkan di layanan mandiri muncul 

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-mobile#103]
Lihat tangkapan layar dibawah ini : 
<img width="626" alt="image" src="https://github.com/OpenSID/wiki-mobile/assets/59082428/460565af-2ea7-4546-b9b6-21899fb6a30c">
1. Tampilan di layanan madiri muncul 
<img width="538" alt="image" src="https://github.com/OpenSID/wiki-mobile/assets/59082428/4faa8e6e-a367-427e-af61-ca9afbf0d9c8">

2. ini dari tampilan di mobile
![image](https://github.com/OpenSID/wiki-mobile/assets/59082428/6340d36a-00b7-4bec-8e5d-bfe2842714a4)

**Comment by pandigresik** [comment]
![image](https://github.com/OpenSID/wiki-mobile/assets/1853475/4dc06d84-2fb6-4f35-ba0c-7bcacb4a640f)
Kami coba lancar

**Comment by pandigresik** [comment]
![image](https://github.com/OpenSID/wiki-mobile/assets/1853475/74c1eee7-4450-4bd3-a204-8ba8f815f379)
di mobile aman, berarti kemungkinan besar masalah data di server

**Comment by pandigresik** [comment]
![image](https://github.com/OpenSID/wiki-mobile/assets/1853475/4e68ee71-193d-4832-ae90-665718d79833)
mas @vickyrolanda dari data di table program config_id null itu db saya dapat dari mas @apidong 
Jadi data antara program dan program_peserta tidak sesuai. Apakah config_id di table program memang dibolehkan bernilai null ?

**Comment by apidong** [comment]
> ![image](https://user-images.githubusercontent.com/1853475/251313223-4e68ee71-193d-4832-ae90-665718d79833.png) mas @vickyrolanda dari data di table program config_id null itu db saya dapat dari mas @apidong Jadi data antara program dan program_peserta tidak sesuai. Apakah config_id di table program memang dibolehkan bernilai null ?

bukan null pak, harusnya 1. 
untuk bantuan diperbolehkan null, kalau null artinya bantuan tsb dibuat melalui openkab dan hanya bisa di hapus melalui openkab

**Comment by pandigresik** [comment]
> > ![image](https://user-images.githubusercontent.com/1853475/251313223-4e68ee71-193d-4832-ae90-665718d79833.png) mas @vickyrolanda dari data di table program config_id null itu db saya dapat dari mas @apidong Jadi data antara program dan program_peserta tidak sesuai. Apakah config_id di table program memang dibolehkan bernilai null ?
> 
> bukan null pak, harusnya 1. untuk bantuan diperbolehkan null, kalau null artinya bantuan tsb dibuat melalui openkab dan hanya bisa di hapus melalui openkab

itu dari db kemarin, masih asli data di program dan program_peserta

**Comment by pandigresik** [comment]
> > ![image](https://user-images.githubusercontent.com/1853475/251313223-4e68ee71-193d-4832-ae90-665718d79833.png) mas @vickyrolanda dari data di table program config_id null itu db saya dapat dari mas @apidong Jadi data antara program dan program_peserta tidak sesuai. Apakah config_id di table program memang dibolehkan bernilai null ?
> 
> bukan null pak, harusnya 1. untuk bantuan diperbolehkan null, kalau null artinya bantuan tsb dibuat melalui openkab dan hanya bisa di hapus melalui openkab

kalau config_id bernilai 1, maka sudah jelas ada kesalahan ketika menyimpan data. Namun jika config_id null proses penyimpanan data sudah benar karena memang dimungkinkan berisi dengan nilai null. Untuk itu disini yang saya perbaiki kondisi ketika config_id bernilai null

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/opensid-laravel/pull/131
