### ISSUE TITLE
Tambahkan tahun lahir pada opsi di surat keterangan jual beli

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-mobile#104]
saat ini terbatas hanya sampai tahun 2000 
![image](https://github.com/OpenSID/wiki-mobile/assets/59082428/9ec29ed2-ed47-4752-9e03-ca65fbe36e15)

untuk penyeragaman mungkin tidak usah di batasin.

**Comment by yogiperdana** [comment]
Sudah dikerjakan melalui PR https://github.com/OpenSID/mobile/pull/176
