### ISSUE TITLE
Sesuaikan harga produk dengan diskon yang tampil pada mobile. 

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-mobile#105]
<img width="539" alt="image" src="https://github.com/OpenSID/wiki-mobile/assets/59082428/dd2b205f-05a7-4260-9612-cb44ac7c3a16">

dilihat di atas sesuai format bisa sesuaikan yang tampil di mobil sesuai dengan layanan mandiri . 
![image](https://github.com/OpenSID/wiki-mobile/assets/59082428/2c8eb18c-9449-4129-a474-899d8431d1f7)

Yang perlu di sesuaikan : 
1. Format Rupiah  ( Rp. 10.000,00)  
2. Sesuaikan harga dengan diskon seperti tangkapan layar di atas ada yang tidak konsisten.

**Comment by yogiperdana** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/mobile/pull/178
