### ISSUE TITLE
Sesuaikan tampilan data kehadiran perangkat sesuai dengan layanan mandiri

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-mobile#106]
Tampilan di layanan mandiri : 
<img width="547" alt="image" src="https://github.com/OpenSID/wiki-mobile/assets/59082428/1e1c0461-fcb6-470d-8b29-d221a96fd800">

Tampilan dimobile: 
![image](https://github.com/OpenSID/wiki-mobile/assets/59082428/aea87985-a2bd-4bfb-9449-d5e6a2c92e96)

**Comment by yogiperdana** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/mobile/pull/179
