### ISSUE TITLE
Update Flutter 3.10.5

### ISSUE THREAD

**Issue by apidong** [OpenSID/wiki-mobile#107]
penyesuaian dan dibutuhkan untuk upgrade : 
1. Update libraly intl ke versi 0.18
2. ganti librarly date_time_picker

saat ini, dengan flutter versi 3.3.10 versi android yang bisa terpakai adalah versi 2021, agar bisa menggunakan android studio versi terbaru, perlu melakukan upgrade flutter 3.10.5

**Comment by pandigresik** [comment]
Flutter 3.10.5 menggunakan dart versi 3.0.5 otomatis pakai dart versi itu juga ya

**Comment by apidong** [comment]
> Flutter 3.10.5 menggunakan dart versi 3.0.5 otomatis pakai dart versi itu juga ya



> Flutter 3.10.5 menggunakan dart versi 3.0.5 otomatis pakai dart versi itu juga ya

iya pak, saat perintah flutter upgrade di jalankan. otomatis mengupdate versi dart nya juga

**Comment by apidong** [comment]
sudah diperbaiki https://github.com/OpenSID/mobile/pull/182
