### ISSUE TITLE
Melihat daftar arsip surat yang sudah tertanda tangan / arsip

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-mobile#112]

**Comment by apidong** [comment]
- [ ] tampilan daftar arsip surat .
- [ ] pagination halaman arsip surat.
- [ ] fungsi reload halaman arsip.
- [ ] fungsi filter halaman arsip surat.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/mobile-admin-opensid/pull/8
