### ISSUE TITLE
Dari pak ariandi

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/wiki-mobile#12]
1. upload doc supaya bisa img (selain pdf)
2. kompres otomatis
3. surat tanpa syarat masih tetap dianggap wajib di app (https://github.com/OpenSID/wiki-mobile/issues/11)
4. klik hapus dokumen, lalu konfirm batal, tapi doc tetap terhapus.
5. tombol back kadang keluar ke setting nama desa lg
6. adanya info nama desa di halaman login depan.
7. hasil tombol unduh salinan KK dan biodata, nama kades tidak muncul.
8. menu bantuan, belum ada tertulis nama bantuan. hanya tertera peserta bantuan.

**Comment by apidong** [comment]
1. @andifahruddinakas  dari sisi API tidak bisa upload selain pdf. 
2. bisa dijelaskan kompres otomatis seperti apa
7. aplikasi mobile hanya menerima hasil generate dari API. kalau nama kades tidak muncul berarti problem ada di API

**Comment by apidong** [comment]
- [ ] > 1. upload doc supaya bisa img (selain pdf)
- [ ] > 2. kompres otomatis
- [ ] > 3. surat tanpa syarat masih tetap dianggap wajib di app ([Kirim permohonan surat tanpa syarat dokumen #11](https://github.com/OpenSID/wiki-mobile/issues/11))
- [ ] > 4. klik hapus dokumen, lalu konfirm batal, tapi doc tetap terhapus.
- [ ] > 5. tombol back kadang keluar ke setting nama desa lg
- [ ] > 6. adanya info nama desa di halaman login depan.
- [ ] > 7. hasil tombol unduh salinan KK dan biodata, nama kades tidak muncul.
- [ ] > 8. menu bantuan, belum ada tertulis nama bantuan. hanya tertera peserta bantuan.
