### ISSUE TITLE
API proses TTE (khusus akses kepala desa)

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-mobile#123]

**Comment by pandigresik** [comment]
mas @vickyrolanda , @apidong  adakah spesifikasi data yang dikirim oleh mobile dan response yang harus diberikan oleh API ?

**Comment by pandigresik** [comment]
Apakah kita bisa gunakan metode seperti ini :
mobile - opensid_api - opensid
Mobile kirim data ke opensid_api kemudian opensid_api tinggal forward ke opensid saja sehingga semua setting TTE hanya di opensid saja

Saya cek proses TTE sudah ada di {url_opensid}/api/tte/sign_visible

**Comment by vickyrolanda** [comment]
pindah issue https://github.com/OpenSID/opensid-laravel/issues/176
