### ISSUE TITLE
Terjadi error setelah memilih desa

### ISSUE THREAD

**Issue by pandigresik** [OpenSID/wiki-mobile#131]
Hal ini disebabkan karena API gagal mendapatkan data desa, saat ini hanya ditampilkan sebagai halaman kosong di production.
Case ini bisa terjadi misalnya terjadi perubahan app_key di opensid disebabkan restore atau lainnya, karena di di opensid api masih menyimpan app_key yang lama sehingga data app_key menjadi tidak sama.

Solusi :
1. Untuk sementara dapat melakukan clear cache di opensid api dengan perintah **php artisan cache:clear** karena app_key disimpan dalam cache

![image](https://github.com/OpenSID/wiki-mobile/assets/1853475/e8b0f660-9a20-4c3b-ba99-f3f8a9387bfa)

**Comment by pandigresik** [comment]
Setelah perbaikan
![image](https://github.com/OpenSID/wiki-mobile/assets/1853475/43f9ce8d-837c-4ed1-9062-963008ff75c4)

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/opensid-laravel/pull/133
