### ISSUE TITLE
Kepala Keluarga pada Unduhan KK aplikasi android tidak berada diurutan atas

### ISSUE THREAD

**Issue by lausalla** [OpenSID/wiki-mobile#14]
Terdapat perbedaan susunan angota keluarga pada hasil unduhan Kartu Keluarga di aplikasi android dengan di website.. pada aplikasi android Kepala Keluarga tidak berada di urutan teratas

**Comment by apidong** [comment]
sudah diperbaiki melalui https://github.com/OpenSID/opensid-laravel/pull/4
