### ISSUE TITLE
Sediakan demo app mobile

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-mobile#15]
Banyak yg ingin mencoba sendiri aplikasi mobile.

Perlu buatkan demonya. Yaitu sediakan pilihan demo di app-nya. Untuk demo, gunakan API dan OpenSID di berputar.opensid.or.id. 

Jelaskan di app bahwa untuk menggunakan demo perlu juga akses ke berputar.opensid.or.id untuk mendaftar layanan mandiri dan melakukan kegiatan admin yg diinginkan, seperti periksa surat, menerima pesan dsbnya.

Lokasi API dan OpenSID demo tidak di-hardcode. Sediakan pengaturannya. Cari tempat yg paling cocok untuk pengaturannya. Mungkin di Layanan?

**Comment by andifahruddinakas** [comment]
Sudah digabung melalui PR https://github.com/OpenSID/mobile/pull/104
