### ISSUE TITLE
[Penduduk] Unggah dokumen kependudukan menggunakan kamera

### ISSUE THREAD

**Issue by agungsugiarto** [OpenSID/wiki-mobile#16]
Apa kekurangan yg ingin diatasi?

Saat ini berkas dokumen kependudukan hanya bisa diunggah dari file, baik di Admin maupun melalui Layanan Mandiri. Untuk memudahkan, sediakan fitur untuk bisa mengunggah langsung dengan mengambil foto menggunakan kamera HP.

**Comment by scqolbu24** [comment]
issue ini di close dengan pertimbangan issue "#19 [Android/APK [tambah dokumen] mohon untuk dapat menambahkan dokumen dalam bentuk image](https://github.com/OpenSID/wiki-mobile/issues/19)" lebih banyak penjelasannya, dan issue ini sudah termasuk didalamnya
