### ISSUE TITLE
Google Policy - Update Ke "target Android 13 (API level 33)"

### ISSUE THREAD

**Issue by apidong** [OpenSID/wiki-mobile#160]
aturan dari goggle, minimal target yang diperlukan android 13 "api Level 33"

![image](https://github.com/OpenSID/wiki-mobile/assets/20056421/e293cd2f-e35c-4b50-9dd9-f08ee67bc997)

cara update https://ananda-gopal.medium.com/flutter-change-your-apps-target-api-level-to-e2febf5774f2

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/mobile/pull/185
