### ISSUE TITLE
Tampilkan Jumlah Notifikasi dan halaman daftar notifikasi.

### ISSUE THREAD

**Issue by apidong** [OpenSID/wiki-mobile#169]

**Comment by vickyrolanda** [comment]
mas ini beluma da PR , apakah ini sudah di terapkan ya mas?

**Comment by apidong** [comment]
sudah. sepertinya salah tag issue.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/mobile-admin-opensid/pull/33
