### ISSUE TITLE
Sesuaikan logo dan nama aplikasi pada halaman login

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-mobile#17]
Kabupaten Muaro Jambi meminta aplikasi mobile bisa menampilkan logo dan nama aplikasi khusus. Mereka meminta adanya apk berbeda di Google Play Store. Permintaan ini tidak sesuai dengan arah OpenDesa. Alternatifnya adalah menyesuaikan halaman login dan halaman lain di aplikasi mobile mengikuti tema kabupaten.

**Comment by eddieridwan** [comment]
![telegram-cloud-photo-size-5-6323273083825271043-x](https://user-images.githubusercontent.com/249563/152268708-e5932b9d-e99a-488e-8b55-da05f0073786.jpg)

**Comment by andifahruddinakas** [comment]
Sudah digabung melalui PR https://github.com/OpenSID/mobile/pull/104
