### ISSUE TITLE
Jenis surat pada layanan mandiri mobile tidak muncul

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-mobile#177]
1. Jika di cek pada halaman layanan mandiri jenis surat muncul untuk di pilih 
![image](https://github.com/OpenSID/wiki-mobile/assets/59082428/e74213dc-d806-436f-8dee-ba3b49361243)

2. namun pada halaman mobile jenis surat tidak tampil 
![image](https://github.com/OpenSID/wiki-mobile/assets/59082428/3f83782e-39a4-4b4c-8a93-ffe2a7222e35)

**Comment by FirlianiF** [comment]
Ketika saya cek di mobile, jenis layanan nya berhasil muncul, berikut screen shoot nya.

![Screenshot 2023-11-07 104152](https://github.com/OpenSID/wiki-mobile/assets/30171560/c4720dfd-c79f-4efd-92c5-8472e4a99284)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/opensid-laravel/pull/205
