### ISSUE TITLE
Tampilan app android di hp oppo F5 terpotong 

### ISSUE THREAD

**Issue by apidong** [OpenSID/wiki-mobile#18]
Tampilan app android di hp oppo F5 terpotong yang mengakibatkan tombol login tidak bisa terlihat.
![image](https://user-images.githubusercontent.com/20056421/154647248-f0bd8126-ccf0-40c3-8c55-6a019b300fe3.png)

detail model hp :
Model CPH1723
Versi android 7.1.1

**Comment by andifahruddinakas** [comment]
Sudah digabung melalui PR https://github.com/OpenSID/mobile/pull/104
