### ISSUE TITLE
Kota Bima - Default untuk sebutan desa.

### ISSUE THREAD

**Issue by apidong** [OpenSID/wiki-mobile#180]
Saat terjadi error seperti Request time out, dll. 
sebutan desa mengikuti kondisi default yaitu desa, sehingga seolah-olah ini adalah bug.
solusinya : 
gunakan FlavorConfig untuk membuat default pada opensid umum dan opensid kota bima.

Alur : 
 1. variable sebutan desa sudah terdapat pada masing2 file utama apk. jadi tinggal tentukan default pada tampilan yang dibutuhkan
 2. panggil varibale sebutan desa menggunakan  FlavorConfig.instance.variables["sebutan_desa"].toString()

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/mobile/pull/193
