### ISSUE TITLE
Kota bima - Logo default Aplikasi

### ISSUE THREAD

**Issue by apidong** [OpenSID/wiki-mobile#181]
Saat terjadi error seperti Request time out, dll.
Logo desa menjadi gambar default, sehingga seolah-olah ini adalah bug.
solusinya :
gunakan FlavorConfig untuk membuat default pada opensid umum dan opensid kota bima.

Alur :
1. Masukkan logo ke dalam folder assets/images/
2. buat variable baru di bagian  FlavorConfig pada masing2 main file. variable tersebut berisi lokasi logo di folder tersebut.
3. pada file screen yang memuat logo, ubah default logo aplikasi berdasarkan varibale di FlavorConfig.

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/mobile/pull/194
