### ISSUE TITLE
Ganti Kata-kata TTE saat modal passphrase tampil

### ISSUE THREAD

**Issue by apidong** [OpenSID/wiki-mobile#184]
![image](https://github.com/OpenSID/wiki-mobile/assets/20056421/318e70b8-7859-4e81-ae90-7040dab2db6e)

- [ ] ganti kata TTE menjadi Tandatangan Elektronik
- [ ] Ubah tipe input menjadi password

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/mobile-admin-opensid/pull/37
