### ISSUE TITLE
tambahakan form komentar pada artikel di opensid mobile

### ISSUE THREAD

**Issue by ai-skematik** [OpenSID/wiki-mobile#2]
saat ini telah tersedia artikel di opensid mobile tapi belum dilengkapi form komentar sebagaimana artikel web. sehingga saran saya disamakan seperti opensid web. dan komentar pada opensid mobile tidak perlu memasukkan kode capta karena sudah dilakukan login sebelumnya.

**Comment by apidong** [comment]
sudah diperbaiki melalui https://github.com/OpenSID/mobile/pull/108
