### ISSUE TITLE
Error Login Kelola Desa

### ISSUE THREAD

**Issue by apidong** [OpenSID/wiki-mobile#207]
![image](https://github.com/OpenSID/wiki-mobile/assets/20056421/7c4d5895-4d67-4653-96b2-00e1e8cb4e74)

![image](https://github.com/OpenSID/wiki-mobile/assets/20056421/a17cedce-24f7-4c22-964c-84e678ac8e66)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/mobile-admin-opensid/pull/57
