### ISSUE TITLE
Error Pada Halaman Riwayat Permohonan Surat

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-mobile#22]
Pada Halaman Permohonan Surat terdapat error Right Overflowed By 11 Pixels.
issue ini muncul pada saat menggunakan OPPO A16.

![riwayat-permohonan](https://user-images.githubusercontent.com/68048807/159293747-52637e37-dac8-4840-88fe-4ecdafd2be79.jpg)

**Comment by scqolbu24** [comment]
Dibuka kembali karena ketika panjang karakter judul permohonan dan status surat akan membuat error pada lebar dan tinggi.
berikut tampilan erorr : 
![riwayat permohonan surat1](https://user-images.githubusercontent.com/68048807/160807924-decbe3bd-4e55-450f-8b99-94df1fad76bb.jpg)

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/mobile/pull/115
