### ISSUE TITLE
bug : tidak terjadi penjumlahan pada modul statistik

### ISSUE THREAD

**Issue by apidong** [OpenSID/wiki-mobile#228]
contoh kasus desa lubuk lawas
![image](https://github.com/OpenSID/wiki-mobile/assets/20056421/52c8df8f-d9a8-4a74-9699-5b9411bfdd94)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/mobile-admin-opensid/pull/66
