### ISSUE TITLE
Daftar Kehadiran Perangkat tidak tampil - kasus Desa Sadar Sriwijaya Provinsi Kab Lampung Timur Kec Bandar Sribhawono

### ISSUE THREAD

**Issue by apidong** [OpenSID/wiki-mobile#232]
![image](https://github.com/OpenSID/wiki-mobile/assets/20056421/eca0197e-b31e-4661-9359-c55567ed98d9)
tampilan di layanan mandiri 
![image](https://github.com/OpenSID/wiki-mobile/assets/20056421/5f42cba2-d1a4-436a-b5f7-07e53a1cc09b)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/mobile/pull/211
