### ISSUE TITLE
Bug/error: saat pengajuan surat tidak ada jenis surat yang mau dipilih pemohon

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/wiki-mobile#234]
Jelaskan error yg dialami :
saat pengajuan surat tidak ada jenis surat yang mau dipilih

Cara untuk mereplikasi errornya :

1. Form Pengajuan surat
2. Pilih Jenis Surat Pemohon 

Tangkapan layar dan log error :

![image](https://github.com/OpenSID/wiki-mobile/assets/55429781/24040c29-ab1d-464b-9ce8-8a01ef40689b)

**Comment by vickyrolanda** [comment]
- solusi sudah di tambahkan di forum OpenDesa
