### ISSUE TITLE
List Dokumen yang sudah dihapus masih ditampilkan

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-mobile#24]
Saat ini pada list dokumen di mobile data yang sudah dihapus masih ditampilkan seperti pada tangkapan layar berikut :

![dokumenall](https://user-images.githubusercontent.com/68048807/159826545-ea199742-8d0b-4e10-89d2-169b3abde1b7.jpg)

data pada tanggal 03 February 2022 sudah dihapus namun masih ditampilkan, seharusnya list dokumen ditmapilkan seperti pada Layanan Mandiri, berikut tangkapan layarnya:
<img width="100%" alt="dokumen layanan mandiri" src="https://user-images.githubusercontent.com/68048807/159826782-42211575-ab7b-4325-a3ef-6f24afa8695e.PNG">

Solusi yang diharapkan, list yang tampil di layanan mandiri hanya data yang aktif/belum dihapus.

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/opensid-laravel/pull/10
