### ISSUE TITLE
Jumlah laporan bulanan kependudukan di aplikasi keloladesa tidak sama

### ISSUE THREAD

**Issue by apidong** [OpenSID/wiki-mobile#241]
![image](https://github.com/OpenSID/wiki-mobile/assets/20056421/26e849ac-910c-4bd1-b49b-7fb633c1521c)
![image](https://github.com/OpenSID/wiki-mobile/assets/20056421/c5cd3859-10ef-44b2-8bc8-17de7b36345f)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/mobile-admin-opensid/pull/74
