### ISSUE TITLE
tulisan beranda jika panjang akan turun ke bawah dan membuat tampilan menjadi keluar dari kotak

### ISSUE THREAD

**Issue by apidong** [OpenSID/wiki-mobile#243]
![image](https://github.com/OpenSID/wiki-mobile/assets/20056421/80290a87-acfd-4aa6-81d5-e0c8f2e7c47b)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/mobile-admin-opensid/pull/77
