### ISSUE TITLE
Absen Via App KelolaDesa Tercatat Tidak Sesuai Dengan Waktu Setempat

### ISSUE THREAD

**Issue by emanuel-simon** [OpenSID/wiki-mobile#248]
1. Jika absen masuk menggunakan aplikasi KelolaDesa, di Rekapitilasi Kehadiran tercatat 1 jam lebih lambat, jadi  absen jam 9, tercatat jam 8
2. Tapi jika absen masuk lewat laman Kehadiran di web, tidak ada perbedaan, absen jam 9 tercatat jam 9
3. Apakah fitur kehadiran di aplikasi keloladesa menggunakan zona waktu WIB?
4. Saya berada di zona WITA

![Screenshot_20240705_090358](https://github.com/OpenSID/wiki-mobile/assets/48465803/25da9c33-f8df-4c78-9d5e-a7b8d2bc241c)

![2024-07-04_10h49_54](https://github.com/OpenSID/wiki-mobile/assets/48465803/6ebd06de-5bc2-4600-af06-a99ae65bed9f)

**Jika aplikasi KelolaDesa Menggunakan Zona Waktu, diharapkan dapat menyesuaikan dengan lokasi pengguna, agar absen yang tercatat di Rekapitulasi Kehadiran sesuai dengan waktu setempat.**

**Comment by apidong** [comment]
@vickyrolanda issue ini karena pengaturannya masih menggunakan id/jakarta. 
ini sudah dibuatkan perbaikaanya melalui issue https://github.com/OpenSID/opensid-api/issues/362

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/opensid-api/pull/363
