### ISSUE TITLE
Aplikasi mobile kelolaDesa terdapat pemberitauan "Tidak bisa masuk, Terdeteksi device tidak aman" 

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/wiki-mobile#249]
Jelaskan error yg dialami : 

Aplikasi mobile kelolaDesa terdapat pemberitauan "Tidak bisa masuk, Terdeteksi device tidak aman" , menyebabkan aplikasi keloladesa tidak bisa digunakan, terjadi disemua hape perangkat desa

Hasil yg diharapkan :

Aplikasi bisa normal kembali

Screenshoot Error "

![image](https://github.com/user-attachments/assets/33fb242d-70aa-4c32-b5f2-4bd58d44d4d9)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/mobile-admin-opensid/pull/80
