### ISSUE TITLE
Menyederhanakan form Keterangan

### ISSUE THREAD

**Issue by khiar-rara** [OpenSID/wiki-mobile#251]
![opensidmobile_issue](https://github.com/user-attachments/assets/ea056366-25f4-48f0-964e-de152f09b552)

Saat ini ada 2 form Keterangan yang ditampilkan pada pengajuan surat di aplikasi LayananDesa yaitu "Keterangan Tambahan" dan "Keterangan". Bisakah ini disederhanakan untuk meminimalkan isian, misal dihapus salah satu atau Isian di form keterangan pertama "Keterangan Tambahan" kembali diperlihatkan pada isian di form kedua "Keterangan".

**Comment by pandigresik** [comment]
Keterangan tambahan dan keterangan surat pada sisi sebelah kanan (selanjutnya) itu 2 hal yang berbeda. Untuk keterangan sebelah kanan itu bergantung pada inputan form di OpenSID dan bisa jadi tidak ada inputan tersebut, meskipun saat ini sebagian besar pada surat ada inputan keterangan. Menurut kami biarkan saja seperti sekarang ini

**Comment by khiar-rara** [comment]
Ya kalau di inputan suratnya tidak ada form keterangan, untuk apa ditampilkan.

**Comment by khiar-rara** [comment]
Jika masih ingin dipertahankan seperti saat ini, mohon untuk judul "Keterangan Tambahan" dapat diganti menjadi "Pesan untuk Operator" atau lainnya biar langsung dimengerti

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/mobile/pull/218
