### ISSUE TITLE
Aplikasi KelolaDesa tidak bisa digunakan untuk Absensi

### ISSUE THREAD

**Issue by rgrahardi** [OpenSID/wiki-mobile#258]
1. Menu Kehadiran tidak bisa digunakan pada Aplikasi KelolaDesa, untuk titik lokasi kantor sudah di tentutkan di aplikasi OpenSID

![image](https://github.com/user-attachments/assets/a94899b3-acd1-4dbb-878f-7ab447453526)

![image](https://github.com/user-attachments/assets/2844c978-58c0-4c4d-b4ce-e425813a2c1a)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/mobile-admin-opensid/pull/84
