### ISSUE TITLE
Error Tampilan Arsip Surat

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-mobile#26]
Pada Halaman Arsip Surat terdapat error Bottom Overflowed By 14 Pixels.
issue ini muncul pada saat menggunakan OPPO A16.
![arsip surat](https://user-images.githubusercontent.com/68048807/160788434-61c994da-3d08-4b0d-bfa3-28c42a0c5e65.jpg)

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/mobile/pull/114
