### ISSUE TITLE
bug : Desa https://angseri.desa.id/ - KelolaDesa - data SDGSnya tidak Sesuai dengan desa Angseri

### ISSUE THREAD

**Issue by apidong** [OpenSID/wiki-mobile#260]
![image](https://github.com/user-attachments/assets/5262cb13-dd02-4b12-a64f-c49c77326a43)
![image](https://github.com/user-attachments/assets/f9c06617-b915-4ce1-9757-68e780bed19e)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/mobile-admin-opensid/pull/86
