### ISSUE TITLE
bug tidak bisa tampilkan halaman idm

### ISSUE THREAD

**Issue by apidong** [OpenSID/wiki-mobile#261]
![image](https://github.com/user-attachments/assets/907ac85f-6b5c-481c-b563-19fe9df1402e)

masalah ssl di domain api id,
solusi, matikan verifikasi ssl

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/mobile-admin-opensid/pull/87
