### ISSUE TITLE
Error Tampilan Pesan Kotak Masuk dan Pesan Keluar

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-mobile#27]
Pada Halaman Pesan Kotak Masuk dan Kotak Keluar terdapat error Bottom Overflowed By 3.9 Pixels.
issue ini muncul pada saat menggunakan OPPO A16.

![pesan masuk](https://user-images.githubusercontent.com/68048807/160788797-23fe705d-b397-47e6-830e-86597a089f8a.jpg)

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/mobile/pull/116
