### ISSUE TITLE
Penamaan NIK

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-mobile#29]
Penamaan Nik seharusnya menggunakan huruf kapital yaitu NIK

![nik](https://user-images.githubusercontent.com/68048807/162685746-c95ef444-7dda-472c-ac8b-23d605349507.jpg)

**Comment by agungsugiarto** [comment]
Sudah diperbaiki melalui pr https://github.com/OpenSID/mobile/pull/119
