### ISSUE TITLE
Hasil unduhan salinan KK di OpenSID mobile default lanscape

### ISSUE THREAD

**Issue by ai-skematik** [OpenSID/wiki-mobile#3]
saat ini hasil unduhan kk di opensid mobil posisi portrait, sebaiknya hasil unduhan kk posisi lanscape sebagaimana cetakan kk pada umumnya.

**Comment by scqolbu24** [comment]
Sekarang fitur ini sudah tersedia, yaitu ketika unduh kk posisi sudah landscape, maka dari itu issue ini kami tutup. terimakasih.
