### ISSUE TITLE
Berita headline ketika di klik tidak terjadi apa-apa

### ISSUE THREAD

**Issue by apidong** [OpenSID/wiki-mobile#31]
saat klik headline tidak terjadi apa-apa.
![image](https://user-images.githubusercontent.com/20056421/175894881-2f35cd71-32f7-4c34-9af0-71a8362cef8f.png)

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/mobile/pull/121
