### ISSUE TITLE
Ketika pilih menu Artikel tidak muncul di opensid mobile dan foto slider masih mucul padahal di menu admin sudah di gembok

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/wiki-mobile#36]
Ketika pilih menu Artikel tidak muncul di opensid mobile dan foto slider masih mucul padahal di menu admin sudah di gembok.

https://forum.opendesa.id/d/194-artikel-tidak-muncul

**Comment by scqolbu24** [comment]
Apakah versi yang dipakai sudah versi yang terbaru ?
Kemudian jika sudah yang terbaru jalankan perintah "composer update"

**Comment by devrakapriyo** [comment]
akan saya pastikan dulu ke pengguna di forum, nanti akan saya update kembali hasilnya.

**Comment by apidong** [comment]
mungkin ini masalah chace di api.
nanti akan saya cek terlebih dahulu

**Comment by apidong** [comment]
@devrakapriyo setelah saya cek, semuanya karena chace.
solusi yang bisa dilakukan

untuk mematikan slider:

1. matikan slider .

![image](https://user-images.githubusercontent.com/20056421/186225895-70008ac0-2f4e-498b-af66-601c13e24d56.png)

2. jalankan perintah **php artisan cache:clear** di server API
3. jalankan perintah **php artisan optimize** di server API

**untuk artikel :**

1. pastikan artikel berada di dalam kategori berita desa. jika tidak, artikel tidak akan tampil di opensid android
![image](https://user-images.githubusercontent.com/20056421/186226167-08cb899e-57c8-44d0-ab8a-d57f45c5b385.png)
2. jalankan perintah **php artisan cache:clear** di server API
3. jalankan perintah **php artisan optimize** di server API

**Comment by scqolbu24** [comment]
@vickyrolanda perlu adanya analisis terlebih dahulu.

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/opensid-laravel/pull/24
