### ISSUE TITLE
Menambah nomor operator desa di halaman depan aplikasi 

### ISSUE THREAD

**Issue by fatholboy2021** [OpenSID/wiki-mobile#37]
Bisa tidak menambahkan nomor kontak operator desa di halaman depan aplikasi opensid versi android

**Comment by scqolbu24** [comment]
sudah dikerjakan melalaui PR:
https://github.com/OpenSID/premium/pull/1960
https://github.com/OpenSID/opensid-laravel/pull/48
https://github.com/OpenSID/mobile/pull/152

**Comment by andifahruddinakas** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/premium/pull/1960
