### ISSUE TITLE
Tambahkan jenis surat tinymce di layanan mandiri sesuai pengaturan di operator.

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-mobile#39]
1. Saat ini surat tinymce sudah tersedia di layanan mandiri web maka perlu di sesuaikan juga untuk di mobilenya.

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/opensid-laravel/pull/40
