### ISSUE TITLE
[ui/ux] - Pada halaman login sediakan tombol kembali untuk memilih desa

### ISSUE THREAD

**Issue by agungsugiarto** [OpenSID/wiki-mobile#4]
<img width="203" alt="image" src="https://user-images.githubusercontent.com/10989147/143670533-24f67f04-5806-4318-8b86-d688b59c61b5.png">

Pada halaman login sediakan tombol untuk memilih desa dan clear local storage yg sebelumnya sudah tersimpan (digenerate ulang).

**Comment by apidong** [comment]
![image](https://user-images.githubusercontent.com/20056421/143763952-cad14482-ff62-4672-8892-70e2de68bca6.png)
seperti ini gmna mas @agungsugiarto

**Comment by apidong** [comment]
diperbaiki di https://github.com/OpenSID/mobile/pull/80
