### ISSUE TITLE
saat lupa PIN, keterangan email tidak sesuai

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/wiki-mobile#47]
saat lupa PIN, keterangan email tidak sesuai sedangkan email yang dimasukan merupakan email yang digunakan untuk login

![image](https://user-images.githubusercontent.com/36557759/188314574-260a5085-a7d5-4e8a-8875-b25176bff394.png)

**Comment by apidong** [comment]
untuk error ini. saya coba dilokal dikarenakan ada pengaturan env yang kurang. seperti 
MAIL_MAILER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=7768318f2c9bd2
MAIL_PASSWORD=347ae06ca82b3b
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDRESS=email@gmail.com
 field di atas wajib terisi semua

**Comment by apidong** [comment]
untuk mengetahui apakah sudah sesuai saya buat perbaikan terhadap pesan eerrornya

**Comment by devrakapriyo** [comment]
cara mengeceknya dimana ya mas?

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/mobile/pull/131
