### ISSUE TITLE
memperjelas sebutan PIN atau Password

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/wiki-mobile#48]
ini berlaku di halaman login dan lupa password, karena antar halaman berbeda penyebutan
maka perlu di penyeragaman penyebutan

**Comment by apidong** [comment]
@devrakapriyo maksudnya seperti apa mas, di ganti menjadi pin saja seperti itu kah?

**Comment by devrakapriyo** [comment]
iya mas, diubah istilahnya jadi PIN saja

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/mobile/pull/133
