### ISSUE TITLE
perbaikan format datetime di halaman detail pesan

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/wiki-mobile#49]
![image](https://user-images.githubusercontent.com/36557759/188314975-51759a9a-c61e-4d6c-b50a-2b86139a35da.png)

seharusnya format datetimenya 03 September 2022 06:57

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/mobile/pull/132
