### ISSUE TITLE
[ui/ux] - Pada halaman login sesuaikan input pin, keyboard otomatis berupa angka.

### ISSUE THREAD

**Issue by agungsugiarto** [OpenSID/wiki-mobile#5]
<img width="202" alt="image" src="https://user-images.githubusercontent.com/10989147/143670626-1a5f4b98-2299-4341-803e-35cd0f3fba04.png">

Pada halaman login sesuaikan input pin, keyboard otomatis berupa angka.

**Comment by apidong** [comment]
![image](https://user-images.githubusercontent.com/20056421/143774662-9ee4f4ad-33ae-4a27-8bbc-6e66f0b8e701.png)

sudah diperbaiki di https://github.com/OpenSID/mobile/pull/76
