### ISSUE TITLE
BUG: Ketika tekan tombol logout tidak berfungsi

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-mobile#55]
Ketika menakan tombol keluar tidak dapat berfungsi.
cara mereplikasi:
1. Tekan Menu Profil yang ada di Dasbor atau di menu bawah
2. tekan tombol keluar

**Comment by apidong** [comment]
@scqolbu24 tidak bisa duplikasi error. saya coba normal semua

**Comment by scqolbu24** [comment]
@apidong, baik mas, saya sudah coba kembali normal, sepertinya kemarin terkait koneksi atau loading laptopnya yang terlalu lama. 

Issue ini ditutup.
