### ISSUE TITLE
Slider dan artikel tidak muncul

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/wiki-mobile#57]
Setelah melakukan update versi OpenSID 22.10-premium, android dan API Slider dan Artikel tidak muncul

![42A6214C-A554-4CD7-BC53-F9CFC1B53E20](https://user-images.githubusercontent.com/36557759/193576175-f048fc08-aa3e-4748-b5b6-ab93e814145b.jpeg)

**Comment by vickyrolanda** [comment]
mas @devrakapriyo Perlu di check versi API yang di gunakan.

**Comment by devrakapriyo** [comment]
sebab : slider di mobile OpenSID tidak muncul dikarenakan di pengaturan web galeri belum di aktifkkan
solusi : jika web galeri belum di aktifkan di web OpenSID, maka slider di OpenSID mobile hidden saja

**Comment by devrakapriyo** [comment]
mas @apidong dan mas @vickyrolanda 

sebab : slider di mobile OpenSID tidak muncul dikarenakan di pengaturan web galeri belum di aktifkan
solusi : jika web galeri belum di aktifkan di web OpenSID, maka slider di OpenSID mobile hidden saja

**Comment by apidong** [comment]
baik

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/mobile/pull/137
