### ISSUE TITLE
fitur notifikasi tidak bisa login apabila mobile APP version di update dan API server OpenSID belum update

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/wiki-mobile#58]
setelah berdiskusi dengan pak @ariandii apakah memungkinkan di sediakan fitur ini? karena banyak pengguna sudah update mobile APP di Playstore sedangkan API server OpenSID nya belum update sehingga beberapa fungsi tidak berjalan dengan optimal.

Solusinya : sediakan fitur notifikasi tidak bisa login jika API server OpenSID nya belum update yang terbaru

Perlu diperhatikan : jika API server OpenSID sudah update yang terbaru, sedangkan beberapa pengguna mobile APP belum update bahkan tidak bisa update di Playstore karena keterbatasan OS Android di smartphone nya sudah mentok, maka perlu di carikan solusinya atau diberi tau ke pengelola server OpenSID sebelum melakukan update API server OpenSID perlu dipertimbangkan terkait ketentuan ini

mas @vickyrolanda tolong dibantu analisis juga ya

**Comment by apidong** [comment]
@devrakapriyo jika yang dimaksud adalah incompatibility versi OS android, biasanya Di playstore app tersebut tidak akan muncul jika dilakukan pencarian atau tombol installnya disable.

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR #138 https://github.com/OpenSID/mobile/pull/138
Tampilan Jika versi mobile dan OpenSID API tidak sesuai.
![version mobile](https://user-images.githubusercontent.com/68048807/197961528-4436d161-0777-41ce-9a8f-a9726845da60.jpg)
