### ISSUE TITLE
Desa bukan pelanggan premium tampil sebagai pilihan di app mobile

### ISSUE THREAD

**Issue by eddieridwan** [OpenSID/wiki-mobile#59]
### Kasus Kab Gresik

Edwin Sulistiyo melaporkan di app mobile terlihat ada 10 desa di Gresik yg bisa dipilih:

![telegram-cloud-photo-size-5-6217226218118427798-y](https://user-images.githubusercontent.com/249563/196080455-d194cba2-b06b-47f7-ad22-435a6976e35b.jpg)

![telegram-cloud-photo-size-5-6217226218118427809-y](https://user-images.githubusercontent.com/249563/196080576-d6fcabf1-fa8e-4181-a94d-b76d07a4aa9a.jpg)

Baris 4 dan 8 bukan premium. Perlu diperbaiki supaya hanya desa pelanggan Premium yang tampil. Dalam kasus Kab Gresik berarti hanya 8 desa.

**Comment by FirlianiF** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/145
