### ISSUE TITLE
seragamkan huruf kapital pada pemilihan daerah

### ISSUE THREAD

**Issue by devrakapriyo** [OpenSID/wiki-mobile#60]
<img width="1440" alt="Screen Shot 2022-10-07 at 15 30 17" src="https://user-images.githubusercontent.com/36557759/196877324-fa1d244b-202a-428a-9317-2343e4f90ec8.png">

saat ini nama daerah penulisan huruf besar di awal atau kapital pada saat memilih daerah belum rapih seperti gambar di atas, harap sesuaikan menjadi capital

**Comment by scqolbu24** [comment]
sudah sesuai menggunakan huruf kapital semua, dikerjakan melalui PR https://github.com/OpenSID/mobile/pull/139.
![review mobile](https://user-images.githubusercontent.com/68048807/197952003-dffee845-775c-4ad9-a8c0-c71bd29d191e.jpg)
