### ISSUE TITLE
Eror Blank Merah pada Ajukan Surat Lewat Aplikasi Layanan Mandiri Mobile

### ISSUE THREAD

**Issue by mah-mudi** [OpenSID/wiki-mobile#64]
Tidak bisa ajukan surat lewat aplikasi mobile OpenSID
![134e5976-814e-4992-9f5a-0a4b51870011](https://user-images.githubusercontent.com/57661283/201810334-4a759ae0-9b1e-4f85-875c-baa983bbfecb.jpg)
Sudah ada syarat KK, KTP dan dokumen syarat sdh diupload.

API OpenSID sudah versi v.22.11.01
![image](https://user-images.githubusercontent.com/57661283/201810773-cb4282c7-4818-4bc4-9715-ebc1f676d62d.png)
![image](https://user-images.githubusercontent.com/57661283/201811127-c538a27f-a3c7-4f6a-83d6-7e0d9093dafb.png)

Aplikasi OpenSID yg dijalankan sudah versi v.22.11.01
![6fcbf14f-bea2-4bad-b178-7825412c0c3c](https://user-images.githubusercontent.com/57661283/201810894-753b983a-f83a-454a-82d1-7ffa534391ff.jpg)

Sudah Update juga
![image](https://user-images.githubusercontent.com/57661283/201811390-83303edf-458b-4e85-b4da-f8eaaa68fa37.png)
![image](https://user-images.githubusercontent.com/57661283/201811482-88b326cd-2915-4820-9f51-5c82b2c151d9.png)

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/mobile/pull/141
