### ISSUE TITLE
[bug] - Beberapa hp mengalami masalah pada halaman beranda nama desa, kecamatan, kabupaten dan logo desa tidak muncul

### ISSUE THREAD

**Issue by agungsugiarto** [OpenSID/wiki-mobile#7]

**Comment by apidong** [comment]
![image](https://user-images.githubusercontent.com/20056421/143673707-e83168bf-706e-4a45-9e7d-77f4d88583ba.png)

untuk memudahkan menelusuri penyebabnya. saya tampilkan penyebab errornya.

**Comment by apidong** [comment]
karena error keluar pada hp tertentu, sehingga sulit untuk duplikasi error-nya. untuk sementara saya tampilkan pesan error. 
https://github.com/OpenSID/mobile/pull/77

**Comment by scqolbu24** [comment]
Issue ini tidak dapat direplikasi dan sudah ditanyakan digrup telegram belum ada yang melaporkan ulang masalah ini, sehingga issue ini dututup.
