### ISSUE TITLE
Unhandled Exception: PlatformException(Exception encountered, read, javax.crypto.BadPaddingException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT

### ISSUE THREAD

**Issue by apidong** [OpenSID/wiki-mobile#70]
![image](https://user-images.githubusercontent.com/20056421/210204631-227f1e7c-ef3c-49c1-9d09-88473cf994cf.png)

refrensi di forum git : https://github.com/mogol/flutter_secure_storage/issues/354

**Comment by scqolbu24** [comment]
sudah diperbaiki melalui PR https://github.com/OpenSID/mobile/pull/150
