### ISSUE TITLE
matikan akses ke Mobile kalau masa langganan Premium telah berakhir

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/wiki-mobile#71]
jika masa langganan Premium telah berakhir, maka desa masih bisa terus menggunakan rilis OpenSID terakhir yg mereka gunakan. 

Tetapi apakah saat ini mereka masih bisa terus menggunakan aplikasi PBB dan Mobile (versi yg terakhir mereka gunakan)?

Sepertinya kita perlu matikan akses ke PBB dan Mobile kalau masa langganan Premium telah berakhir.

Pak Eddie Ridwan, [19/12/2022 10:26]
Terlihat jumlah pelanggan Premium di Lampung dan tempat lain menurun karena tidak memperpanjang. Hanya berlangganan satu tahun saja. Perlu dipikirkan apa yg perlu kita lakukan supaya desa diberi motivasi untuk meneruskan langganan Premium.

Pak Eddie Ridwan, [19/12/2022 10:28]
@HerryWanda Salah satu opsi adalah seperti di atas. OpenSID dapat terus digunakan pada versi terakhir yg digunakan. Tetapi dari awal PBB dan Mobile kita nyatakan khusus untuk pelanggan Premium. Jadi saya kira cukup konsisten kalau akses ke PBB dan Mobile hilang jika tidak lagi berlangganan Premium.

**Comment by apidong** [comment]
Untuk desa yang sudah habis langganannya atau tidak premium, sudah tidak tampil di pilihan desa.
