### ISSUE TITLE
Kota Bima - Konfig Pilih desa berdasarkan hanya untuk kota bima

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-mobile#74]
- [x] Perlu disesuaikan agar desa yang tampil hanya kota bisa saja 
- [x] Pilih provinsi & kota tidak lagi diperlukan maka otomatis hanya ada pilihan desa saja

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/mobile/pull/159
