### ISSUE TITLE
Kota Bima - Tambahkan modul multi app  

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-mobile#75]
- [x] Perlu di coba untuk membuat apps Kota bima & apps mobile umum dapat dibuat di 1 repo 
- [x] Maka beberapa hal perlu diperhatikan seperti asset logo , icon apps perlu disesuaikan di masing -masing app
- [ ] Lalu juga ada perbedaan konfig pilih desa dimana Kota Bima hanya dapat pilih desanya saja tanpa perlu pilih provinsi lain dan kota lain.

**Comment by apidong** [comment]
> * [ ]  Perlu di coba untuk membuat apps Kota bima & apps mobile umum dapat dibuat di 1 repo
> * [ ]  Maka beberapa hal perlu diperhatikan seperti asset logo , icon apps perlu disesuaikan di masing -masing app
> * [ ]  Lalu juga ada perbedaan konfig pilih desa dimana Kota Bima hanya dapat pilih desanya saja tanpa perlu pilih provinsi lain dan kota lain.

point ke 3 di pindah ke issue https://github.com/OpenSID/wiki-mobile/issues/74

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/mobile/pull/157
