### ISSUE TITLE
Teknis - Permudah pemanggilan di terminal untuk build

### ISSUE THREAD

**Issue by apidong** [OpenSID/wiki-mobile#78]
saat ini untuk build 2 aplikasi, command harus diketik masing-masing aplikasi. agar mempermudah, di harapkan command diketik sekali  akan mem-build semua aplikasi yang ada di android
solusi : gunakan node js untuk mengumpulkan masing-masing command dan gunakan js untuk menjalankan perintah

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/mobile/pull/161
