### ISSUE TITLE
Buat panduan untuk membuat multi APK dan custom tema seperti kota Bima

### ISSUE THREAD

**Issue by apidong** [OpenSID/wiki-mobile#79]

**Comment by apidong** [comment]
![image](https://github.com/OpenSID/wiki-mobile/assets/20056421/6bb6a4fc-03d7-4f33-aa04-c16d0585e714)
@scqolbu24  siap riview 
ada di panduan https://panduan.opendesa.id/id/opensid-mobile/dokumentasi/pengembangan

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui panduan https://panduan.opendesa.id/id/opensid-mobile/dokumentasi/pengembangan#build-aab-untuk-keperluan-upload-ke-playstore
