### ISSUE TITLE
Ubah kata-kata Desa Menjadi kelurahan 

### ISSUE THREAD

**Issue by apidong** [OpenSID/wiki-mobile#81]

**Comment by eddieridwan** [comment]
@apidong pastikan menggunakan pengaturan sebutan, seperti di OpenSID. Tidak di-hard-code. Seharusnya bisa terdeteksi dari kode wilayah. Kalau tidak salah di Permendagri terkait ada info yg mana kelurahan dan yg desa -- cek di TrackSID.

**Comment by apidong** [comment]
> @apidong pastikan menggunakan pengaturan sebutan, seperti di OpenSID. Tidak di-hard-code. Seharusnya bisa terdeteksi dari kode wilayah. Kalau tidak salah di Permendagri terkait ada info yg mana kelurahan dan yg desa -- cek di TrackSID.

untuk form awal pemilihan desa, harus hard-code karena belum ada pemilihan desa. saya buat hard-codenya seperti pengaturan di file config opensid. 
![image](https://user-images.githubusercontent.com/20056421/231422548-284b9369-f0fb-477c-8a16-9db14bf95c83.png)

untuk selanjutnya, sebutan desa bisa diambil dari API Opensid.

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/mobile/pull/164
