### ISSUE TITLE
Link WA dan Foto produk pelapak tdk bisa terbuka

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/wiki-mobile#85]
Saat ingin membuka WA pelapak pada produk tertentu, makaa akan menampilkan halamaana errror.

![Screenshot_2023-05-04-07-15-39-75_7bd1e93dfbd7033a92739b1867380b15.jpg](https://user-images.githubusercontent.com/57283157/236071595-d7eace12-3718-424e-afc4-5e8842ed6edf.jpg)

![Screenshot_2023-05-04-07-15-44-72_7bd1e93dfbd7033a92739b1867380b15.jpg](https://user-images.githubusercontent.com/57283157/236071606-b5434a3d-c475-44d4-baf3-1c227edf1fce.jpg)

**Comment by apidong** [comment]
agar support semua device, dimana tidak semua device menginstall WA. maka link WA di ganti menggunakan SMS

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/mobile/pull/168
