### ISSUE TITLE
Versi Terbaru di PS

### ISSUE THREAD

**Issue by andifahruddinakas** [OpenSID/wiki-mobile#86]
Versi terbaru did PS saat ini adalah 2304.0.0 seharusnya 2305.0.0 (kalau ada perbaikan). Sehingga saat buka aplikasi menampilkan notifikasi untuk update aplikasi.

![Screenshot_2023-05-04-07-21-24-61_7bd1e93dfbd7033a92739b1867380b15.jpg](https://user-images.githubusercontent.com/57283157/236072024-bc0b7a57-00b5-4a17-8dc4-eaf7ce9fcb63.jpg)

**Comment by apidong** [comment]
https://play.google.com/store/apps/details?id=com.opensid sudah di update? silahkan di cek ulang @andifahruddinakas
