### ISSUE TITLE
Halaman beranda -  Logo dan Gambar Tidak Tampil.

### ISSUE THREAD

**Issue by apidong** [OpenSID/wiki-mobile#87]
![image](https://github.com/OpenSID/wiki-mobile/assets/20056421/13931e93-a54f-447c-89de-dbd0f50e2a61)

**Comment by apidong** [comment]
sudah dibuatkan panduan melalui https://panduan.opendesa.id/id/opensid-mobile/dokumentasi/panduan-error#logo-dan-gambar-tidak-tampil

**Comment by andifahruddinakas** [comment]
> sudah dibuatkan panduan melalui https://panduan.opendesa.id/id/opensid-mobile/dokumentasi/panduan-error#logo-dan-gambar-tidak-tampil

belum bisa mengecek ini karena `http://api.berputar.opendesa.id/healthcheck` masih bermaslah

**Comment by eddieridwan** [comment]
@andifahruddinakas apakah sudah ada issue dan ada yg ditugaskan untuk menindaklanjuti masalah http://api.berputar.opendesa.id/healthcheck?

**Comment by andifahruddinakas** [comment]
Masalah healtcheck ada di issue https://github.com/OpenSID/opensid-laravel/issues/106

Sudah pernah di cek sama mas @apidong

**Comment by apidong** [comment]
> Masalah healtcheck ada di issue [OpenSID/opensid-laravel#106](https://github.com/OpenSID/opensid-laravel/issues/106)
> 
> Sudah pernah di cek sama mas @apidong

server siap pakai bermasalah dengan server ftpnya, sedang dicek tapi masih belum ketemu masalahnya

**Comment by apidong** [comment]
@scqolbu24 sudah di pindahkan ke https://panduan.opendesa.id/id/opensid-mobile/instalasi#masalah-instalasi

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui panduan https://panduan.opendesa.id/id/opensid-mobile/instalasi#masalah-instalasi
