### ISSUE TITLE
Panduan Login Mobile

### ISSUE THREAD

**Issue by scqolbu24** [OpenSID/wiki-mobile#89]
**Jika Eror dibawah tidak dapat login solusinya adalah jalankan `php artisan jwt:secret` pada OpenSID API**
![Image](https://user-images.githubusercontent.com/68048807/238793616-998893c6-e53b-440c-b4c4-72254a027720.jpeg)

**Jika status ftp pada healtcheck adalah `false` maka dapat login namun tidak dapat menampilkan gambar** 
![Image](https://user-images.githubusercontent.com/68048807/238793125-a06f8c25-42db-406b-baba-413d3045e14f.png)

![Image](https://user-images.githubusercontent.com/68048807/238794083-df525b18-7a9d-4c79-9078-53e1815d153d.jpg)

![Image](https://user-images.githubusercontent.com/68048807/238794115-f526b85f-a3e3-4e42-9e5e-0e5b2244e67b.jpeg)

**Jika status ftp pada healtcheck adalah `true` maka dapat login dan dapat menampilkan gambar**
![Image](https://user-images.githubusercontent.com/68048807/238793393-7cae2cc2-d6fe-415a-afb3-fd9ae51d1dae.png)

![Image](https://user-images.githubusercontent.com/68048807/238794202-9d460f98-89ca-41f1-b5ea-bd2764b1717b.jpeg)

![Image](https://user-images.githubusercontent.com/68048807/238794213-a1b0dc8b-7099-4a06-8267-dd2302f446f5.jpeg)

**Comment by apidong** [comment]
sudah dibuatkan panduan di https://panduan.opendesa.id/id/opensid-api/instalasi#internal-server-error

**Comment by scqolbu24** [comment]
sudah dibuatkan panduan https://panduan.opendesa.id/id/opensid-api/instalasi#internal-server-error
