### ISSUE TITLE
Bug : Arsip surat ditandatangani null

### ISSUE THREAD

**Issue by apidong** [OpenSID/wiki-mobile#90]
![image](https://github.com/OpenSID/wiki-mobile/assets/20056421/db2313c3-99f8-432f-914e-daec1e1c25d4)

![image](https://github.com/OpenSID/wiki-mobile/assets/20056421/b5568a12-7250-4d6c-b400-89d3ae702abd)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/opensid-laravel/pull/117
