### ISSUE TITLE
bug : error bagikan artikel 

### ISSUE THREAD

**Issue by apidong** [OpenSID/wiki-mobile#91]
![image](https://github.com/OpenSID/wiki-mobile/assets/20056421/02bfd12e-24a4-418e-aea5-a117703c93a2)

bagikan artikel ke wa dan telegram, termasuk misal klik bagikan twitter namun tidak jadi, maka tombol kembali tidak berfungsi.

**Comment by yogiperdana** [comment]
Sudah diperbaiki melalui PR https://github.com/OpenSID/mobile/pull/172
