### ISSUE TITLE
Bug : Loading terus saat simpan modul pengaduan

### ISSUE THREAD

**Issue by apidong** [OpenSID/wiki-mobile#92]
replikasi : 
1. buka modul pengaduan
2. dalam kondisi kosong, simpan pengaduan.
![image](https://github.com/OpenSID/wiki-mobile/assets/20056421/8f0a7d17-5e0b-403f-91dc-260478e7c71a)

**Comment by vickyrolanda** [comment]
Sudah diselesaikan di PR https://github.com/OpenSID/mobile/pull/170
