### ISSUE TITLE
Unggah Dokumen gagal muncul pesan error ftp_fput(); could not create file

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-mobile#95]
1. bug ini sangat dibutuhkan agar aplikasi mobile dapat digunakan mohon periksa bagian unggah document pada aplikasi mobile setiap ingin unggah selalu muncul error **ftp_fput(); Could not create file** pada aplikasi.

**Comment by apidong** [comment]
ini karena permision dari folder desa pak, yang perlu dilakukan 
1. ubah permisi folder desa > upload menjadi 775
2. masukan grup user fpt ke dalam group www-data
panduan https://panduan.opendesa.id/id/dasbor-siappakai/instalasi#instal-ftp
![image](https://github.com/OpenSID/wiki-mobile/assets/20056421/fe3ea728-8858-423b-8a7d-dc6c5a6b38e2)

**Comment by vickyrolanda** [comment]
https://panduan.opendesa.id/id/dasbor-siappakai/instalasi#instal-ftp
