### ISSUE TITLE
Unduh Biodata Lengkap tidak dpat diproses

### ISSUE THREAD

**Issue by vickyrolanda** [OpenSID/wiki-mobile#96]
1. masuk ke aplikasi mobile
2. klik ke profil
3. lalu klik Lihat Profile Lengkap
4. klik Unduh Biodata 
5. tampilan yang tampil hanya loading yang cukup lama

**Comment by apidong** [comment]
saya cek normal.
![image](https://github.com/OpenSID/wiki-mobile/assets/20056421/cd863423-12a3-4f16-b505-74c229eac186)
terjadi di desa mana pak?

**Comment by vickyrolanda** [comment]
sudah diperbaiki
